
# Program config file

number_of_producers: 15
number_of_consumers: 15
pointer_array_size: 10
source_file: ../zad1/PrideAndPrejudice-JaneAusten.txt
magic_number_length: 40
search_mode: 0
log_mode: 0
nk: 0

# search_mode = {-1 : LESS_THAN | 0 : EQUAL | 1 : GREATER_THAN }
# log_mode = {0 : SIMPLIFIED | 1 : FULL}